% Enter your MATLAB code below
% http://www.mathworks.com/help/matlab/ref/annotationtextbox-properties.html

currentTemp = thingSpeakRead(265494,'Field',1);
% use static dat instead of current temp
currentTemp = 22.9;

annotation('textbox',[0.0 0.4 0.9 0.6],...
 'HorizontalAlignment','right',...
 'VerticalAlignment','middle',...
 'LineStyle','none',...
 'String',['23.4 °C (max)'],...
 'Color','0.5 0.5 0.5',...
 'FontSize',28);
 
annotation('textbox',[0.0 0.2 0.9 0.6],...
 'HorizontalAlignment','right',...
 'VerticalAlignment','middle',...
 'LineStyle','none',...
 'String',[num2str(currentTemp) '°C'],...
 'Color','0.224 0.651 0.518',...
 'FontSize',72);
 
annotation('textbox',[0.0 0.0 0.9 0.6],...
 'FontName','FixedWidth',...
 'HorizontalAlignment','right',...
 'VerticalAlignment','middle',...
 'LineStyle','none',...
 'String',['20.8 °C (min)'],...
 'Color','0.5 0.5 0.5',...
 'FontSize',28);
 
